# Generated by Django 3.2.5 on 2021-07-07 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoppinglist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='担当'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.item', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='shoppinglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.shoppinglist', verbose_name='ショッピングリスト'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.category', verbose_name='カテゴリ'),
        ),
    ]
