databases:
  - name: django_shoppinglist
    region: oregon
    user: shoppinglist

services:
  - type: web
    name: django_shoppinglist
    env: python
    region: oregon
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.wsgi'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: django_shoppinglist
          property: connectionString
    autoDeploy: true
